apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbits
data:
  enabled_plugins: |
    [rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672

    cluster_formation.peer_discovery_backend  = k8s
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = rabbitmq

  ################################ To import definitions (https://www.rabbitmq.com/definitions.html)
  ## definitions.skip_if_unchanged = true
  ## definitions.import_backend = local_filesystem
  ## definitions.local.path = /path/to/definitions/conf.d/